# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Where\'sBaby' do
pod 'IHKeyboardAvoiding', :git => 'https://github.com/hxx0215/IHKeyboardAvoiding'
pod 'Masonry'
pod 'MBProgressHUD'
pod 'JSONKit-NoWarning'
pod 'AFNetworking'
pod 'SWRevealViewController'
pod 'JSQMessagesViewController'
pod 'SDWebImage', '~>3.7'
end

